COMPILER = gcc

CSTD = --std=c18

# Define  paths  to other  header  files  we need to use.

INCLUDES = ../array_list

LIBFLAGS = -lm

MAIN = ~/CSCI2122/Labs/lab5/bmurray/CI/objects/array_list/arrayM.o


array_list: array_list.c array_list.h $(MAIN)
	$(COMPILER) $(CSTD) $(LIBFLAGS) array_list.c $(MAIN) 